steps:
  #build docker container
  #- name: 'gcr.io/cloud-builders/docker'
  #  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/moodshop/frontend_moodshop:$SHORT_SHA', '.']
  - name: 'docker/compose:alpine-1.29.2'
    args: [ 'up', '-d' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'tag', 'gcr.io/moodshop-315102/moodshop/frontend', 'gcr.io/$PROJECT_ID/moodshop/frontend_moodshop:$SHORT_SHA' ]

    #push container to container registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/moodshop/frontend_moodshop:$SHORT_SHA' ]

    # deploy container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=Kubernetes.yaml
      - --image=gcr.io/$PROJECT_ID/moodshop/frontend_moodshop:$SHORT_SHA
      - --location=${_CLOUDSDK_COMPUTE_ZONE}
      - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}


    #deploy to cloud run
#- name: 'gcr.io/cloud-builders/gcloud'
#  args:
#  - 'run'
#  - 'deploy'
#  - 'moodshop-service'
#  - '--image'
#  - 'gcr.io/$PROJECT_ID/moodshop/frontend_moodshop:$SHORT_SHA'
#  - '--region'
#  - 'us-central1'
#  - '--platform'
#  - 'managed'
#  - '--allow-unauthenticated'
images:
  - 'gcr.io/$PROJECT_ID/moodshop/frontend_moodshop:$SHORT_SHA'
