version: "3.8"
services:
  api:
    image: zakimaulana/apimoodshop:master
    ports:
      - "8089-8090:8089"
    env_file:
      - ./api/.env
    networks:
      - moodshopnet
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
    volumes:
      - ./shared-api:/shared-files
  redis:
    image: redis:5.0.10-alpine
    env_file: 
      - ./redis/.env
    ports:
      - "8999:6379"
    networks:
      - moodshopnet
    depends_on:
      - api
    restart: always
    mem_limit: 50M
    cpus: "0.50"
  frontend:
    image: zakimaulana/frontendmoodshop:master
    restart: unless-stopped
    ports:
      - "8588:80"
    env_file:
      - ./frontend/.env
    networks:
      - moodshopnet
    depends_on: 
      - api
networks:
  moodshopnet:
    driver: bridge
