apiVersion: v1
kind: Namespace
metadata:
  name: production
---
apiVersion: v1
data:
  MODE: DEV
  DB_HOST: 54.227.229.162
  DB_USER: cormac
  DB_PASS: c0b4d1b4c4
  DB_DATABASE: moodshop
  DB_PORT: 5432
  REDIS_HOST: 54.227.229.162
  REDIS_PORT: 6379
  REDIS_PASS: c0b4d1b4c4
  JWT_KEYS: rahasiakuterbongkarsudah
  CLOUD_KEY: 676327326565441
  CLOUD_SECRET: A4FazLHEsU2TArM4oWcjVxSJZM4
  CLOUD_NAME: devops-engineer
  CLOUD_ENV: cloudinary://676327326565441:A4FazLHEsU2TArM4oWcjVxSJZM4@devops-engineer

kind: ConfigMap
metadata:
  name: env-backend
  namespace: production
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: production
spec:
  selector:
    matchLabels:
      app: frontend-vue
      tier: frontend
  template:
    metadata:
      labels:
        app: frontend-vue
        tier: frontend
    spec:
      containers:
        - name: frontendmoodshop
          image: zakimaulana/frontendmoodshop:master
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 3
---
#SERVICES for moodshop frontend
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: production
spec:
  selector:
    app: frontend-vue
    tier: frontend
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30122
      protocol: TCP
      name: frontendport

--- 
# DEPLOYMENT FOR BACKEND
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-vue
      tier: backend
  template:
    metadata:
      labels:
        app: api-vue
        tier: backend
    spec:
      containers:
        - name: apimoodshop
          image: zakimaulana/apimoodshop:master
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8089
          envFrom:
          - configMapRef:
              name: env-backend
          livenessProbe:
            httpGet:
              path: /health
              port: 8089
            initialDelaySeconds: 5
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8089
            initialDelaySeconds: 5
            periodSeconds: 3
---
#SERVICE FOR API
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: production
spec:
  selector:
    app: api-vue
    tier: backend
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8089
      nodePort: 30123
      protocol: TCP
      name: backendport
---
# INGRESS
